### ISSUE TITLE
Must run update.php if manually updating DB

### ISSUE THREAD

**Issue by freephile** [freephile/meza#106]
### Environment

- Machine or Virtual Machine details: Digital Ocean
- Operating System: (run `cat /etc/redhat-release` and report output)
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
- meza version hash: (`meza --version`)

Meza 39.7.0-8-g530c3a0
Commit 530c3a0e82c3e7d7a348fadb975331a6074f0659
Mediawiki EZ Admin

### Issue details

I imported the database dump from the old 'wiki' 

`meza --version`
Meza 31.10.1-305-ge61ab45
Commit e61ab45253d2142a9cd3c4bd0e3c871f60d2e308
Mediawiki EZ Admin

into wiki_greg and got a DB error about needing to run **update.php**

```

Deprecated: Premature access to service container [Called from BootstrapComponents\HookRegistry::registerMyConfiguration in /opt/htdocs/mediawiki/extensions/BootstrapComponents/src/HookRegistry.php at line 381] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'HookContainer' [Called from MediaWiki\MediaWikiServices::getInstance in /opt/htdocs/mediawiki/includes/MediaWikiServices.php at line 289] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'ObjectFactory' [Called from Wikimedia\Services\ServiceContainer::{closure} in /opt/htdocs/mediawiki/includes/ServiceWiring.php at line 721] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'ConfigFactory' [Called from BootstrapComponents\HookRegistry::registerMyConfiguration in /opt/htdocs/mediawiki/extensions/BootstrapComponents/src/HookRegistry.php at line 381] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381

Deprecated: Premature access to service 'BootstrapConfig' [Called from Wikimedia\Services\ServiceContainer::{closure} in /opt/htdocs/mediawiki/includes/ServiceWiring.php at line 414] in /opt/htdocs/mediawiki/includes/debug/MWDebug.php on line 381
MediaWiki internal error.

Original exception: [ZrtMonajAzxWfsfMRdS4zwAAANg] /greg/Honda_ST1300A/electrical?requestDebug=1 Wikimedia\Rdbms\DBQueryError: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading or after adding a new extension?

Please see https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Upgrading and https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:How_to_debug for more information.

Error 1054: Unknown column 'rev_actor' in 'field list'
Function: MediaWiki\Revision\RevisionStore::fetchRevisionRowFromConds
Query: SELECT rev_id,rev_page,rev_timestamp,rev_minor_edit,rev_deleted,rev_len,rev_parent_id,rev_sha1,comment_rev_comment.comment_text AS `rev_comment_text`,comment_rev_comment.comment_data AS `rev_comment_data`,comment_rev_comment.comment_id AS `rev_comment_cid`,actor_rev_user.actor_user AS `rev_user`,actor_rev_user.actor_name AS `rev_user_text`,rev_actor,page_namespace,page_title,page_id,page_latest,page_is_redirect,page_len,user_name FROM `revision` JOIN `revision_comment_temp` `temp_rev_comment` ON ((temp_rev_comment.revcomment_rev = rev_id)) JOIN `comment` `comment_rev_comment` ON ((comment_rev_comment.comment_id = temp_rev_comment.revcomment_comment_id)) JOIN `actor` `actor_rev_user` ON ((actor_rev_user.actor_id = rev_actor)) JOIN `page` ON ((page_id = rev_page)) LEFT JOIN `user` ON ((actor_rev_user.actor_user != 0) AND (user_id = actor_rev_user.actor_user)) WHERE rev_id = 10842 LIMIT 1

Backtrace:
from /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1618)
#0 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException(string, integer, string, string)
#1 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#2 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#3 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1711): Wikimedia\Rdbms\Database->query(string, string, integer)
#4 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1720): Wikimedia\Rdbms\Database->select(array, array, array, string, array, array)
#5 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->selectRow(array, array, array, string, array, array)
#6 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(344): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#7 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2402): Wikimedia\Rdbms\DBConnRef->selectRow(array, array, array, string, array, array)
#8 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2967): MediaWiki\Revision\RevisionStore->fetchRevisionRowFromConds(Wikimedia\Rdbms\DBConnRef, array)
#9 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1689): MediaWiki\Revision\RevisionStore->MediaWiki\Revision\{closure}(boolean, integer, array, NULL, array)
#10 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1522): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array)
#11 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2972): WANObjectCache->getWithSetCallback(string, integer, Closure)
#12 /opt/htdocs/mediawiki/includes/page/WikiPage.php(781): MediaWiki\Revision\RevisionStore->getKnownCurrentRevision(Title, integer)
#13 /opt/htdocs/mediawiki/includes/page/WikiPage.php(806): WikiPage->loadLastEdit()
#14 /opt/htdocs/mediawiki/includes/page/WikiPage.php(668): WikiPage->getRevisionRecord()
#15 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1689): WikiPage->{closure}(boolean, integer, array, NULL, array)
#16 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1522): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array)
#17 /opt/htdocs/mediawiki/includes/page/WikiPage.php(687): WANObjectCache->getWithSetCallback(string, integer, Closure, array)
#18 /opt/htdocs/mediawiki/includes/page/WikiPage.php(296): WikiPage->getContentModel()
#19 /opt/htdocs/mediawiki/includes/MediaWiki.php(437): WikiPage->getContentHandler()
#20 /opt/htdocs/mediawiki/includes/MediaWiki.php(320): MediaWiki->initializeArticle()
#21 /opt/htdocs/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#22 /opt/htdocs/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#23 /opt/htdocs/mediawiki/index.php(50): MediaWiki->run()
#24 /opt/htdocs/mediawiki/index.php(46): wfIndexMain()
#25 {main}

Exception caught inside exception handler: [ZrtMonajAzxWfsfMRdS4zwAAANg] /greg/Honda_ST1300A/electrical?requestDebug=1 Wikimedia\Rdbms\DBQueryError: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading or after adding a new extension?

Please see https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:Upgrading and https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:How_to_debug for more information.

Error 1054: Unknown column 'rev_actor' in 'field list'
Function: MediaWiki\Revision\RevisionStore::fetchRevisionRowFromConds
Query: SELECT rev_id,rev_page,rev_timestamp,rev_minor_edit,rev_deleted,rev_len,rev_parent_id,rev_sha1,comment_rev_comment.comment_text AS `rev_comment_text`,comment_rev_comment.comment_data AS `rev_comment_data`,comment_rev_comment.comment_id AS `rev_comment_cid`,actor_rev_user.actor_user AS `rev_user`,actor_rev_user.actor_name AS `rev_user_text`,rev_actor,page_namespace,page_title,page_id,page_latest,page_is_redirect,page_len,user_name FROM `revision` JOIN `revision_comment_temp` `temp_rev_comment` ON ((temp_rev_comment.revcomment_rev = rev_id)) JOIN `comment` `comment_rev_comment` ON ((comment_rev_comment.comment_id = temp_rev_comment.revcomment_comment_id)) JOIN `actor` `actor_rev_user` ON ((actor_rev_user.actor_id = rev_actor)) JOIN `page` ON ((page_id = rev_page)) LEFT JOIN `user` ON ((actor_rev_user.actor_user != 0) AND (user_id = actor_rev_user.actor_user)) WHERE rev_id = 10842 LIMIT 1

Backtrace:
from /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1618)
#0 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException(string, integer, string, string)
#1 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#2 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#3 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1711): Wikimedia\Rdbms\Database->query(string, string, integer)
#4 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1720): Wikimedia\Rdbms\Database->select(array, array, array, string, array, array)
#5 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->selectRow(array, array, array, string, array, array)
#6 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(344): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#7 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2402): Wikimedia\Rdbms\DBConnRef->selectRow(array, array, array, string, array, array)
#8 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2967): MediaWiki\Revision\RevisionStore->fetchRevisionRowFromConds(Wikimedia\Rdbms\DBConnRef, array)
#9 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1689): MediaWiki\Revision\RevisionStore->MediaWiki\Revision\{closure}(boolean, integer, array, NULL, array)
#10 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1522): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array)
#11 /opt/htdocs/mediawiki/includes/Revision/RevisionStore.php(2972): WANObjectCache->getWithSetCallback(string, integer, Closure)
#12 /opt/htdocs/mediawiki/includes/page/WikiPage.php(781): MediaWiki\Revision\RevisionStore->getKnownCurrentRevision(Title, integer)
#13 /opt/htdocs/mediawiki/includes/page/WikiPage.php(806): WikiPage->loadLastEdit()
#14 /opt/htdocs/mediawiki/includes/page/WikiPage.php(668): WikiPage->getRevisionRecord()
#15 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1689): WikiPage->{closure}(boolean, integer, array, NULL, array)
#16 /opt/htdocs/mediawiki/includes/libs/objectcache/wancache/WANObjectCache.php(1522): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array)
#17 /opt/htdocs/mediawiki/includes/page/WikiPage.php(687): WANObjectCache->getWithSetCallback(string, integer, Closure, array)
#18 /opt/htdocs/mediawiki/includes/page/WikiPage.php(296): WikiPage->getContentModel()
#19 /opt/htdocs/mediawiki/includes/page/WikiPage.php(282): WikiPage->getContentHandler()
#20 /opt/htdocs/mediawiki/includes/page/Article.php(2071): WikiPage->getActionOverrides()
#21 /opt/htdocs/mediawiki/includes/actions/ActionFactory.php(264): Article->getActionOverrides()
#22 /opt/htdocs/mediawiki/includes/actions/ActionFactory.php(364): MediaWiki\Actions\ActionFactory->getAction(string, Article, RequestContext)
#23 /opt/htdocs/mediawiki/includes/context/RequestContext.php(305): MediaWiki\Actions\ActionFactory->getActionName(RequestContext)
#24 /opt/htdocs/mediawiki/includes/context/ContextSource.php(129): RequestContext->getActionName()
#25 /opt/htdocs/mediawiki/extensions/CodeMirror/includes/Hooks.php(30): ContextSource->getActionName()
#26 /opt/htdocs/mediawiki/extensions/CodeMirror/includes/Hooks.php(44): MediaWiki\Extension\CodeMirror\Hooks::isCodeMirrorOnPage(OutputPage)
```

**Comment by freephile** [comment]
`WIKI=greg php /opt/htdocs/mediawiki/maintenance/update.php --quick` fixes it
