### ISSUE TITLE
Extension:Flow deprecation errors

### ISSUE THREAD

**Issue by freephile** [freephile/meza#26]
```
Deprecated
: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Model/UserTuple.php
on line
55


Deprecated
: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Model/UserTuple.php
on line
55


Deprecated
: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Model/UserTuple.php
on line
55


Deprecated
: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Model/UserTuple.php
on line
55


Deprecated
: property_exists(): Passing null to parameter #2 ($property) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Formatter/AbstractQuery.php
on line
223


Deprecated
: property_exists(): Passing null to parameter #2 ($property) of type string is deprecated in
/opt/htdocs/mediawiki/extensions/Flow/includes/Formatter/AbstractQuery.php
on line
223
```

**Comment by freephile** [comment]
can't just use 'master' because then we get this:
```
fatal error: Uncaught ExtensionDependencyError: Flow is not compatible with the current MediaWiki core (version 1.39.6), it requires: >= 1.42. in /opt/htdocs/mediawiki/includes/registration/ExtensionRegistry.php:432 Stack trace: #0 /opt/htdocs/mediawiki/includes/registration/ExtensionRegistry.php(276): ExtensionRegistry->readFromQueue(Array) #1 /opt/htdocs/mediawiki/includes/Setup.php(278): ExtensionRegistry->loadFromQueue() #2 /opt/htdocs/mediawiki/includes/WebStart.php(86): require_once('/opt/htdocs/med...') #3 /opt/htdocs/mediawiki/index.php(44): require('/opt/htdocs/med...') #4 {main} thrown in /opt/htdocs/mediawiki/includes/registration/ExtensionRegistry.php on line 432
```

**Comment by freephile** [comment]
Test page: https://localhost/demo/index.php/Talk:Main_Page

**Comment by freephile** [comment]
Looking at [the difference between master and REL1_39](https://github.com/wikimedia/mediawiki-extensions-Flow/compare/REL1_39...master), I discovered the patches that were made to 'master' and should be backported to the REL1_39 branch. They are listed in https://gerrit.wikimedia.org/r/q/topic:T321691

1. https://github.com/wikimedia/mediawiki-extensions-Flow/commit/9e0533a9a27a7f37c4bbebf191ffe9c38ac4a4d4
2. https://github.com/wikimedia/mediawiki-extensions-Flow/commit/0c4d312a0c23e3c24639dedcbb8b76a7b724aa4b
3. https://github.com/wikimedia/mediawiki-extensions-Flow/commit/3dda8494eb9f24a19fe098aab2a6e63ad2d7d3ac

**Comment by freephile** [comment]
Cherry-picking those 3 commits (which are part of https://phabricator.wikimedia.org/T321691) did eliminate the deprecation warnings on [the test page](https://localhost/demo/index.php/Talk:Main_Page)

I need to either setup a local `git cherry-pick` into Meza (bad)

Or, the best option would be to backport changes through Gerrit into the REL1_39 branch of the Flow extension so that all users of Flow (Structured Discussions) could run on PHP 8.1.

But the process is a lot of work. Create a phab ticket? Then submit patches for review and ultimately merging into the Flow extension? There is no doc.

https://www.mediawiki.org/wiki/Version_lifecycle#Extension_lifecycle_management
https://www.mediawiki.org/wiki/Compatibility#MediaWiki_extensions

**Comment by freephile** [comment]
It's high time I dusted off my gerrit credentials and setup my Windows box for contributing to MediaWiki - so I did 👍 

This is in the hands of Gerrit now
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Flow/+/1007626

**Comment by freephile** [comment]
Trying to find [reviewers](https://github.com/wikimedia/mediawiki-extensions-Flow/graphs/contributors). umherirrender looks recent.  Reedy gave it +2

**Comment by freephile** [comment]
Closing this issue as my commits were merged upstream into the Flow extension, into the REL1_39 branch.
e.g. https://gerrit.wikimedia.org/r/q/I310d872e4722dc47fd94f079bbc9b997f41540da
https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/Flow/+log/refs/heads/REL1_39
