### ISSUE TITLE
Create wiki fails 

### ISSUE THREAD

**Issue by freephile** [freephile/meza#48]
### Environment

- VirtualBox
- Operating System: Rocky Linux release 8.9 (Green Obsidian)
- meza version hash: 1e91f9e
- 1e91f9ed730b7c4c60b8a9d77462dd8b25f0ade9 (HEAD -> REL1_39, origin/REL1_39) Fix permission problems + naming in .smw.json directory

### Issue details

`sudo meza create wiki monolith -vvv` fails, even when all SMW extensions are disabled, at least in part because smw **rebuildData.php** is invoked and loops endlessly - **even after the `meza create` is killed.

The process tree looks like this:

```
/usr/libexec/platform-python /bin/ansible-playbook /opt/meza/src/playbooks/create-wiki.yml -i /opt/conf-meza/secret/monolith/hosts --vault-password-file /opt/conf-meza/vault/vault-pass-monolith.txt --extra-vars {"env": "monolith"}
 158788  158789  158010  158010 ?             -1 S     1002   0:00  \_ /bin/sh -c sudo -H -S -n  -u root /bin/sh -c 'echo BECOME-SUCCESS-skbrwsddhqotndjofqimygueyzbnqnwd ; /usr/bin/python' && sleep 0
 158789  158790  158010  158010 ?             -1 S        0   0:00      \_ sudo -H -S -n -u root /bin/sh -c echo BECOME-SUCCESS-skbrwsddhqotndjofqimygueyzbnqnwd ; /usr/bin/python
 158790  158792  158010  158010 ?             -1 S        0   0:00          \_ /bin/sh -c echo BECOME-SUCCESS-skbrwsddhqotndjofqimygueyzbnqnwd ; /usr/bin/python
 158792  158793  158010  158010 ?             -1 S        0   0:00              \_ /usr/bin/python
 158793  158795  158010  158010 ?             -1 S        0   0:00                  \_ /bin/sh -c bash /opt/.deploy-meza/smw-rebuild-all.sh disc > /opt/data-meza/logs/smw-rebuilddata/smw-rebuild-all.log
 158795  158796  158010  158010 ?             -1 S        0   0:03                      \_ bash /opt/.deploy-meza/smw-rebuild-all.sh disc
 158796  185504  158010  158010 ?             -1 R        0   0:00                          \_ php /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php -d 5 -v --skip-properties --ignore-exceptions --debug --report-runtime --startidfile /opt/data-meza/logs/custom-rebuild-start-id-file -n 1000 --exception-log=/opt/data-meza/logs/smw-rebuilddata-exceptions-disc-2024-03-08_08:31:22.log
```

The rebuildData.php script consumes all available CPU (pegs it) and can't be killed

```
pgrep php | xargs ps fuwww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      213445  0.0  0.5 884856 58204 ?        R    09:02   0:00 php /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php -d 5 -v --skip-properties --ignore-exceptions --debug --report-runtime --startidfile /opt/data-meza/logs/custom-rebuild-start-id-file -n 1000 --exception-log=/opt/data-meza/logs/smw-rebuilddata-exceptions-disc-2024-03-08_08:31:22.log
```
Because, as the log shows, it just keeps spawning new processes.

```
tail /opt/data-meza/logs/smw-rebuilddata-exceptions-disc-2024-03-08_08:31:22.log
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
Start ID not updating. Was 0. Last ID logged = . Incrementing to 1
```

**Comment by freephile** [comment]
I was able to successfully run `sudo meza create wiki monolith` after temporarily disabling (commenting out) calls to `smw-rebuild-all.sh` in
- src/roles/create-wiki-wrapper/tasks/main.yml
- src/playbooks/rebuild-smw-and-index.yml

`sudo meza create wiki monolith -vvv` becomes
`su meza-ansible -c "ansible-playbook /opt/meza/src/playbooks/create-wiki.yml -i /opt/conf-meza/secret/monolith/hosts --vault-password-file /opt/conf-meza/vault/vault-pass-monolith.txt --extra-vars '{\"env\": \"monolith\"}'"`

**Comment by freephile** [comment]
These are some of the 'smells' that you get when create wiki is failing due to old SQL

```
================================================================================
sudo meza create wiki monolith 
would fail with 
================================================================================

TASK [verify-wiki : Setup SMW Store] ***************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "WIKI=\"haulin\" php \"/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php\"\n",
    "delta": "0:00:00.981064",
    "end": "2024-03-07 09:12:39.670238",
    "rc": 1,
    "start": "2024-03-07 09:12:38.689174"
}

STDOUT:

Semantic MediaWiki:                                                   4.1.3
MediaWiki:                                                           1.39.6

STDERR:

Wikimedia\Rdbms\DBQueryError from line 1618 of /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php: Error 1054: Unknown column 'rev_actor' in 'field list'
Function: MessageCache::loadFromDB(en)-small




================================================================================
DETAILED EXAMPLE ERROR
================================================================================

TASK [verify-wiki : Setup SMW Store] ***************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "WIKI=\"t1\" php \"/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php\"\n",
    "delta": "0:00:00.483596",
    "end": "2024-03-08 00:22:37.205812",
    "rc": 1,
    "start": "2024-03-08 00:22:36.722216"
}

STDOUT:

Semantic MediaWiki:                                                   4.1.3
MediaWiki:                                                           1.39.6


STDERR:

Wikimedia\Rdbms\DBQueryError from line 1618 of /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php: Error 1054: Unknown column 'rev_actor' in 'field list'
Function: MessageCache::loadFromDB(en)-small
Query: SELECT  /*! STRAIGHT_JOIN */ rev_id,rev_page,rev_timestamp,rev_minor_edit,rev_deleted,rev_len,rev_parent_id,rev_sha1,comment_rev_comment.comment_text AS `rev_comment_text`,comment_rev_comment.comment_data AS `rev_comment_data`,comment_rev_comment.comment_id AS `rev_comment_cid`,actor_rev_user.actor_user AS `rev_user`,actor_rev_user.actor_name AS `rev_user_text`,rev_actor,page_namespace,page_title,page_id,page_latest,page_is_redirect,page_len  FROM `page` JOIN `revision` ON ((page_id = rev_page)) JOIN `revision_comment_temp` `temp_rev_comment` ON ((temp_rev_comment.revcomment_rev = rev_id)) JOIN `comment` `comment_rev_comment` ON ((comment_rev_comment.comment_id = temp_rev_comment.revcomment_comment_id)) JOIN `actor` `actor_rev_user` ON ((actor_rev_user.actor_id = rev_actor))   WHERE page_is_redirect = 0 AND page_namespace = 8 AND (page_title NOT LIKE '%/%' ESCAPE '`' ) AND (page_len <= 10000) AND (page_latest = rev_id)  














================================================================================
sudo mysql -e 'use wiki_t1; show tables;'
================================================================================

+-----------------------+
| Tables_in_wiki_t1     |
+-----------------------+
| actor                 |
| archive               |
| bot_passwords         |
| category              |
| categorylinks         |
| change_tag            |
| change_tag_def        |
| comment               |
| content               |
| content_models        |
| externallinks         |
| filearchive           |
| image                 |
| imagelinks            |
| interwiki             |
| ip_changes            |
| ipblocks              |
| ipblocks_restrictions |
| iwlinks               |
| job                   |
| l10n_cache            |
| langlinks             |
| log_search            |
| logging               |
| module_deps           |
| objectcache           |
| oldimage              |
| page                  |
| page_props            |
| page_restrictions     |
| pagelinks             |
| protected_titles      |
| querycache            |
| querycache_info       |
| querycachetwo         |
| recentchanges         |
| redirect              |
| revision              |
| revision_actor_temp   |
| revision_comment_temp |
| searchindex           |
| site_identifiers      |
| site_stats            |
| sites                 |
| slot_roles            |
| slots                 |
| templatelinks         |
| text                  |
| updatelog             |
| uploadstash           |
| user                  |
| user_former_groups    |
| user_groups           |
| user_newtalk          |
| user_properties       |
| watchlist             |
+-----------------------+














================================================================================
sudo WIKI=t1 php /opt/htdocs/mediawiki/maintenance/update.php --quick
================================================================================

MediaWiki 1.39.6 Updater

Your composer.lock file is up to date with current dependencies!
Going to run database updates for wiki_t1
...
...
...
Populating externallinks.el_index_60...
el_id 0 - 200 of 
Done, 0 rows updated.
done.
Removing 'externallinks.el_index_60' default value.
Running maintenance/deduplicateArchiveRevId.php...
Deduplicating ar_rev_id...
Wikimedia\Rdbms\DBQueryError from line 1618 of /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php: Error 1146: Table 'wiki_t1.smw_di_wikipage' doesn't exist
Function: SMW\SQLStore\EntityStore\SemanticDataLookup::fetchSemanticDataFromTable
Query: SELECT p.smw_title AS prop, o_id AS id0, o0.smw_title AS v0, o0.smw_namespace AS v1, o0.smw_iw AS v2, o0.smw_sortkey AS v3, o0.smw_subobject AS v4, o0.smw_sort AS v5 FROM `smw_di_wikipage` INNER JOIN `smw_object_ids` AS p ON p_id=p.smw_id INNER JOIN `smw_object_ids` AS o0 ON o_id=o0.smw_id WHERE (s_id=29) AND (p.smw_iw!=':smw') AND (p.smw_iw!=':smw-delete')

#0 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1602): Wikimedia\Rdbms\Database->getQueryException('Table 'wiki_t1....', 1146, 'SELECT p.smw_ti...', 'SMW\\SQLStore\\En...')
#1 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(1576): Wikimedia\Rdbms\Database->getQueryExceptionAndLog('Table 'wiki_t1....', 1146, 'SELECT p.smw_ti...', 'SMW\\SQLStore\\En...')
#2 /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php(952): Wikimedia\Rdbms\Database->reportQueryError('Table 'wiki_t1....', 1146, 'SELECT p.smw_ti...', 'SMW\\SQLStore\\En...', false)
#3 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103): Wikimedia\Rdbms\Database->query('SELECT p.smw_ti...', 'SMW\\SQLStore\\En...', 4)
#4 /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(293): Wikimedia\Rdbms\DBConnRef->__call('query', Array)
#5 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(380): Wikimedia\Rdbms\DBConnRef->query('SELECT p.smw_ti...', 'SMW\\SQLStore\\En...', 4)
#6 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(317): SMW\MediaWiki\Connection\Database->executeQuery(Object(Wikimedia\Rdbms\DBConnRef), 'SELECT p.smw_ti...', 'SMW\\SQLStore\\En...', false)
#7 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(556): SMW\MediaWiki\Connection\Database->readQuery(Object(SMW\MediaWiki\Connection\Query), 'SMW\\SQLStore\\En...')
#8 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php(371): SMW\SQLStore\EntityStore\SemanticDataLookup->fetchFromTable(Object(SMW\MediaWiki\Connection\Query), Object(SMW\SQLStore\PropertyTableDefinition), true, Object(SMW\RequestOptions))
#9 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(308): SMW\SQLStore\EntityStore\SemanticDataLookup->fetchSemanticDataFromTable(29, Object(SMW\DIWikiPage), Object(SMW\SQLStore\PropertyTableDefinition))
#10 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/CachingSemanticDataLookup.php(279): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->fetchFromCache(29, Object(SMW\DIWikiPage), Object(SMW\SQLStore\PropertyTableDefinition))
#11 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(293): SMW\SQLStore\EntityStore\CachingSemanticDataLookup->getSemanticData(29, Object(SMW\DIWikiPage), Object(SMW\SQLStore\PropertyTableDefinition), NULL)
#12 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(233): SMW\SQLStore\EntityStore\EntityLookup->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty), NULL)
#13 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Property/SpecificationLookup.php(136): SMW\SQLStore\SQLStore->getPropertyValues(Object(SMW\DIWikiPage), Object(SMW\DIProperty))
#14 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Schema/SchemaFinder.php(117): SMW\Property\SpecificationLookup->getSpecification(Object(SMW\DIProperty), Object(SMW\DIProperty))
#15 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/DataModel/SequenceMap.php(52): SMW\Schema\SchemaFinder->newSchemaList(Object(SMW\DIProperty), Object(SMW\DIProperty))
#16 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/includes/SemanticData.php(497): SMW\DataModel\SequenceMap::canMap(Object(SMW\DIProperty))
#17 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PredefinedPropertyAnnotator.php(74): SMW\SemanticData->addPropertyObjectValue(Object(SMW\DIProperty), Object(SMWDITime))
#18 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(62): SMW\Property\Annotators\PredefinedPropertyAnnotator->addPropertyValues()
#19 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/Property/Annotators/PropertyAnnotatorDecorator.php(61): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#20 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(157): SMW\Property\Annotators\PropertyAnnotatorDecorator->addAnnotation()
#21 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/RevisionFromEditComplete.php(101): SMW\MediaWiki\Hooks\RevisionFromEditComplete->addPredefinedPropertyAnnotation(Object(SMW\ParserData), NULL)
#22 /opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(618): SMW\MediaWiki\Hooks\RevisionFromEditComplete->process(Object(Title))
#23 /opt/htdocs/mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onRevisionFromEditComplete(Object(WikiPage), Object(MediaWiki\Revision\RevisionStoreRecord), false, Object(User), Array)
#24 /opt/htdocs/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook('RevisionFromEdi...', Array, Array, Array)
#25 /opt/htdocs/mediawiki/includes/HookContainer/HookRunner.php(3227): MediaWiki\HookContainer\HookContainer->run('RevisionFromEdi...', Array)
#26 /opt/htdocs/mediawiki/includes/Storage/PageUpdater.php(1538): MediaWiki\HookContainer\HookRunner->onRevisionFromEditComplete(Object(WikiPage), Object(MediaWiki\Revision\RevisionStoreRecord), false, Object(User), Array)
#27 /opt/htdocs/mediawiki/includes/Storage/PageUpdater.php(942): MediaWiki\Storage\PageUpdater->doCreate(Object(CommentStoreComment))
#28 /opt/htdocs/mediawiki/maintenance/populateArchiveRevId.php(252): MediaWiki\Storage\PageUpdater->saveRevision(Object(CommentStoreComment), 9)
#29 /opt/htdocs/mediawiki/maintenance/populateArchiveRevId.php(119): PopulateArchiveRevId::makeDummyRevisionRow(Object(Wikimedia\Rdbms\DBConnRef))
#30 /opt/htdocs/mediawiki/maintenance/deduplicateArchiveRevId.php(40): PopulateArchiveRevId::checkMysqlAutoIncrementBug(Object(Wikimedia\Rdbms\DBConnRef))
#31 /opt/htdocs/mediawiki/maintenance/includes/LoggedUpdateMaintenance.php(45): DeduplicateArchiveRevId->doDBUpdates()
#32 /opt/htdocs/mediawiki/includes/installer/DatabaseUpdater.php(1066): LoggedUpdateMaintenance->execute()
#33 /opt/htdocs/mediawiki/includes/installer/DatabaseUpdater.php(547): DatabaseUpdater->runMaintenance('DeduplicateArch...', 'maintenance/ded...')
#34 /opt/htdocs/mediawiki/includes/installer/DatabaseUpdater.php(511): DatabaseUpdater->runUpdates(Array, false)
#35 /opt/htdocs/mediawiki/maintenance/update.php(209): DatabaseUpdater->doUpdates(Array)
#36 /opt/htdocs/mediawiki/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#37 /opt/htdocs/mediawiki/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#38 /opt/htdocs/mediawiki/maintenance/update.php(319): require_once('/opt/htdocs/med...')
#39 {main}

Notice: Uncommitted DB writes (transaction from PopulateArchiveRevId::makeDummyRevisionRow) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/TransactionManager.php on line 583

Notice: DB transaction writes or callbacks still pending (User::insertNewUser, MediaWiki\User\ActorStore::acquireSystemActorId, WikiPage::insertOn, CommentStore::createComment, MediaWiki\Revision\RevisionStore::insertRevisionRowOn, CommentStore::insertInternal, MediaWiki\Storage\SqlBlobStore::storeBlob, MediaWiki\Storage\NameTableStore::store, MediaWiki\Revision\RevisionStore::insertContentRowOn, MediaWiki\Storage\NameTableStore::store, MediaWiki\Revision\RevisionStore::insertSlotRowOn, WikiPage::updateRevisionOn, MediaWiki\Storage\NameTableStore::acquireId, MediaWiki\Storage\NameTableStore::acquireId, MediaWiki\User\ActorStore::setUpRollbackHandler, MediaWiki\Storage\NameTableStore::store, MediaWiki\Storage\NameTableStore::store) in /opt/htdocs/mediawiki/includes/libs/rdbms/database/Database.php on line 3760
[userx@localhost ~]$ grep -rl smw_di_wikipage /opt/htdocs/mediawiki/
/opt/htdocs/mediawiki/extensions/PageForms/includes/PF_AutocompleteAPI.php
/opt/htdocs/mediawiki/extensions/SemanticDrilldown/includes/Sql/PropertyTypeDbInfo.php
/opt/htdocs/mediawiki/extensions/SemanticScribunto/tests/phpunit/Unit/ScribuntoLuaEngineTestBase.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/data/config/db-primary-keys.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/docs/architecture/database.schema.md
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/docs/examples/hook.sqlstore.installer.beforecreatetablescomplete.md
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DataItemHandlers/DIWikiPageHandler.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/SemanticDataLookup.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Lookup/EntityUniquenessLookup.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ErrorLookup.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Lookup/MonolingualTextLookup.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Lookup/ProximityPropertyValueLookup.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/PropertyTableInfoFetcher.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/tests/phpunit/SQLStore/EntityIdManagerTest.php
/opt/htdocs/mediawiki/extensions/SemanticMediaWiki/tests/phpunit/SQLStore/PropertyTableInfoFetcherTest.php
```
