### ISSUE TITLE
Add ARA to better understand results and status

### ISSUE THREAD

**Issue by freephile** [freephile/meza#85]
**ARA Records Ansible** making it easier to understand and troubleshoot Ansible automation.

![ara-full-logo](https://github.com/freephile/meza/assets/38368/e11fb677-9cb8-4872-8a88-d132a21ef5ed)

- https://ara.recordsansible.org/
- https://ara.readthedocs.io/en/latest/index.html

The point of using ARA is that it provides a complete logging and reporting interface to your 'deploys' (all Ansible playbook runs) so that you have visibility into your Ansible automation. Meza's current mode of operation is to create (large) log files on disc that you must inspect manually to decipher how things went in the last deploy, and it doesn't offer any real means to compare or summarize the operations over time.

One way to think of ARA is to say that like Kibana is an GUI to Elasticsearch, ARA is a GUI frontend to Ansible.

**Comment by freephile** [comment]
I ran ARA on my dev instance at Digital Ocean, but I did not expose the reporting interface port through HAProxy so I could not see the Django web app. i could only see it on the command line.

I tried this quick HAProxy config, which works on the cli but not through the browser? While a local curl works on both ports 8001 (frontend) and 8000 (backend), a request through the browser times out.
```
frontend ara_web
	bind *:8001 name ara_web
	mode http
	default_backend ara-internal

backend ara-internal
	server ara1 127.0.0.1:8000 check
```

**Comment by freephile** [comment]
Following the README at https://codeberg.org/ansible-community/ara

From a vagrant .venv (You can not use a `--user` install from a Vagrant VM)
`python3 -m pip install "ara[server]"`

(.vmvenv) [meza-ansible@meza-app1-rockylinux config]$ ara --version
**[ara 1.6.1](https://ara.readthedocs.io/en/latest/changelog-release-notes.html#id6)**

(.vmvenv) [meza-ansible@meza-app1-rockylinux config]$ ansible --version
```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Feb  5 2026, 20:19:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-28)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
/usr/local/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible [core 2.11.12] 
```
**ansible [core 2.11.12]**

I tried 
(.vmvenv) [meza-ansible@meza-app1-rockylinux config]$ `ara playbook list`
```
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Creating data & configuration directory: /opt/conf-meza/users/meza-ansible/.ara/server
[ara] Writing default settings to /opt/conf-meza/users/meza-ansible/.ara/server/settings.yaml

"dump()" has been removed, use

  yaml = YAML(typ='unsafe', pure=True)
  yaml.dump(...)

instead of file "/opt/meza/.vmvenv/lib64/python3.6/site-packages/ara/server/settings.py", line 303

        yaml.dump({"default": SETTINGS}, settings_file, default_flow_style=False)
```

And again

(.vmvenv) [meza-ansible@meza-app1-rockylinux config]$ `ara playbook list`
```
[ara] No setting found for SECRET_KEY. Generating a random key...
Internal Server Error: /api/v1/playbooks
Traceback (most recent call last):
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: playbooks

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/generics.py", line 175, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 395, in paginate_queryset
    self.count = self.get_count(queryset)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/rest_framework/pagination.py", line 530, in get_count
    return queryset.count()
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 528, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/models/sql/query.py", line 513, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/meza/.vmvenv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: playbooks
2026-02-21 13:49:00,921 ERROR ara.clients.http: Failed to get on /api/v1/playbooks: {'params': {'order': '-started', 'limit': 50}}
2026-02-21 13:49:00,921 ERROR ara.clients.http: Failed to get on /api/v1/playbooks: {'params': {'order': '-started', 'limit': 50}}
2026-02-21 13:49:00,921 ERROR ara: [Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1
```


Despite the obvious errors, I tried to run the web server anyway which I want to note here because it had interesting output about "**unapplied migrations**" in the Python environment.
`ara-manage runserver`
```
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Using settings file: /opt/conf-meza/users/meza-ansible/.ara/server/settings.yaml
[ara] No setting found for SECRET_KEY. Generating a random key...
[ara] Using settings file: /opt/conf-meza/users/meza-ansible/.ara/server/settings.yaml
Performing system checks...

System check identified no issues (0 silenced).

You have 36 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, api, auth, contenttypes, db, sessions.
Run 'python manage.py migrate' to apply them.
February 21, 2026 - 13:51:08
Django version 3.2.25, using settings 'ara.server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by freephile** [comment]
The message about 'manage.py' appears to be a django web app thing (from ara)
`/usr/local/lib/python3.6/site-packages/ansible_collections/community/general/tests/integration/targets/django_manage/files/base_test/1045-single-app-project/single_app_project/manage.py`

**Comment by freephile** [comment]
I had to `ara-manage migrate` to solve the errors. 

But, still deploys were not being recorded. 

I tried running the playbook directly, and preserving the environment (variable set earlier) to ensure the right ENV is exported, but it still failed to record
`su -p meza-ansible -c "ansible-playbook /opt/meza/src/playbooks/site.yml -i /opt/conf-meza/secret/vagrant/hosts --vault-password-file /opt/conf-meza/vault/vault-pass-vagrant.txt --extra-vars '{\"env\": \"vagrant\"}' -vvv"`

**Comment by freephile** [comment]
> [!TIP]
> Important considerations found at https://ara.readthedocs.io/en/latest/troubleshooting.html for setting up a production system while addressing the overhead introduced by recording everything.

**Comment by freephile** [comment]
ARA's API is built on the [Django REST Framework](https://www.django-rest-framework.org/)

**Comment by freephile** [comment]
Like the [README](https://codeberg.org/ansible-community/ara/src/branch/master/README.md) says, I had to 
`export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"`

**Comment by freephile** [comment]
In development, the main issue I faced was the ara callback was skipped (and so no recording happened during deploys).

```
[WARNING]: Skipping plugin (/usr/local/lib/python3.6/site-
packages/ara/plugins/callback/ara_default.py), cannot load: No module named
'ara'
redirecting (type: modules) ansible.builtin.ufw to community.general.ufw
redirecting (type: callback) ansible.builtin.debug to ansible.posix.debug
redirecting (type: callback) ansible.builtin.debug to ansible.posix.debug
redirecting (type: callback) ansible.builtin.profile_tasks to ansible.posix.profile_tasks
ERROR! Unexpected Exception, this is probably a bug: No module named 'ara'
```

In my vagrant VM, I had to install ara systemwide since it needs to be available to the same python interpreter - so don't install it in a .venv  Leave just debugging tools like linters in the venv

But something is going on with 'sudo' and meza-ansible

`sudo -u meza-ansible ansible --version 2>&1` shows the new python and ansible
```
ansible [core 2.16.3]
  config file = /opt/meza/ansible.cfg
  configured module search path = ['/opt/conf-meza/users/meza-ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /opt/collections
  executable location = /bin/ansible
  python version = 3.12.12 (main, Feb 10 2026, 15:51:22) [GCC 8.5.0 20210514 (Red Hat 8.5.0-28)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

## What pip do we have?
`which pip3.12 || which pip3 && pip3 --version`

## Trying to figure out where ansible came from
```
ls -la /usr/bin/python* && echo "---" && which ansible && rpm -qf /usr/bin/ansible 2>/dev/null || dpkg -S /usr/bin/ansible 2>/dev/null
```

But CoPilot went wild with changes saying that meza-ansible user was using `/bin/ansible` NO IT's NOT! 

`sudo -u meza-ansible bash -c "which ansible && ansible --version | head -5"`
gives a different result (/bin/ansible) vs. being logged in as meza-ansible and `which ansible` (/usr/local/bin/ansible)

And proceeded to upgrade and install pip for python 3.12, and downgrade/change other dependencies that weren't working.

`sudo dnf install -y python3.12-pip`

`[WARNING]: Skipping callback 'ara_default', unable to load due to: No module`

The callback plugin itself is failing to load because ARA's server module tries to import health_check.db when the plugin initializes. This is the core problem. The callback plugin can't function without being able to import the ARA server settings which reference health_check.

The issue: django-health-check 4.0.6 doesn't have a db submodule. ARA expects an older version

`sudo python3.12 -m pip install 'django-health-check<4'`
`ls -la /usr/local/lib/python3.12/site-packages/health_check/ | grep -E "^d|db"`

`pip3.12 show django-health-check && ls -la /usr/local/lib/python3.12/site-packages/health_check/`

The system has SQLite 3.26.0 but Django 5.2 (which was installed as a dependency of ARA) requires SQLite 3.31 or later. This is a system-level limitation of Rocky Linux 8.

I need to either:

- Install a newer SQLite (complex, may break system)
- Downgrade Django to a version that works with SQLite 3.26
- Use a different database backend for ARA (PostgreSQL/MySQL)

Option 2 is the easiest - downgrade Django to 4.2 which supports older SQLite versions.

`sudo python3.12 -m pip install 'Django<5,>=4.2'`

## Simple test
```
cd /opt/meza/config && sudo -u meza-ansible ansible localhost -m ping 2>&1 | grep -iE "warning|error|localhost"
```

## Good test 
```
sudo meza deploy vagrant --check --tags essential-vars 2>&1 | tail -20 && sleep 2 && sudo -u meza-ansible sqlite3 /opt/conf-meza/users/meza-ansible/.ara/server/ansible.sqlite "SELECT id, path, status FROM playbooks ORDER BY id DESC LIMIT 1;"
```

or something like
```
sudo -u meza-ansible sqlite3 /opt/conf-meza/users/meza-ansible/.ara/server/ansible.sqlite "SELECT id, path, status, started FROM playbooks ORDER BY id DESC LIMIT 2;"
```
